# -*- coding: utf-8 -*-
"""Computer Vision - Optical Flow

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1m6k3WbxKtr5M-wvNvfWNSo6lxGJiOgA4
"""

import __main__
import pathlib
import os

try:
    GIT_CMD = __main__.GIT_CMD
except NameError:
    GIT_CMD = 'git'

try:
    ROOT_DIR = __main__.ROOT_DIR
except NameError:
    ROOT_DIR - pathlib.Path('.')

HOME_DIR = pathlib.Path.home().resolve()
ORIG_ROOT = pathlib.Path( '.' ).resolve() 

ROOT_DIR.mkdir(parents = True, exist_ok = True )

IMAGES_DIR = ROOT_DIR / "reveal.js" / "assets" / "images" 
VIDEOS_DIR = ROOT_DIR / "reveal.js" / "assets" / "videos" 
SOUND_DIR = ROOT_DIR / "reveal.js" / "assets" / "sounds" 
DATA_DIR = ROOT_DIR / "reveal.js" / "assets" / "data"

import platform

node = platform.node()

for p in [ "weasyprint", "pygments", "youtube-dl", "jinja2" ]:
    os.system("pip" + " install " + p )

import subprocess
import pathlib
import os
from .cd import cd

def updateGit( url, dirname, root ):
        with cd( root ):
            p = pathlib.Path( dirname )
            if not p.is_dir():
                print("cloning {0} from url {1} root {2}".format( dirname, url, root ), 'git command', GIT_CMD)
                os.system( GIT_CMD + " clone " + url )
            else:
                print("git directory exists")

            with cd( dirname ):
                print("Executing git pull")
                o = None
                try:
                    o = subprocess.check_output(GIT_CMD + " pull", shell=True)
                except subprocess.CalledProcessError:
                    pass
                if ( o ):
                    print( 'git pull:' + o.decode('utf-8') )
            
import subprocess
import pathlib
import os
from .cd import cd

updateGit( "https://github.com/hakimel/reveal.js.git", "reveal.js", ROOT_DIR )

with cd( ROOT_DIR / 'reveal.js' ):
    print("Executing npm install")
    try:
        o = subprocess.check_output("npm install", shell = True)
    except subprocess.CalledProcessError:
        pass
    if ( o ):    
        print( 'npm install:' + o.decode('utf-8') )

with cd( ROOT_DIR ):
    pathlib.Path("reveal.js/assets/images").mkdir( parents = True, exist_ok=True )
    pathlib.Path("reveal.js/assets/videos").mkdir( parents = True, exist_ok=True )

updateGit( "https://github.com/guichristmann/Lecture-VN.git", "Lecture-VN", ROOT_DIR )

import pathlib

with cd(ROOT_DIR):
    print("Creating renpy directory in " + str( ROOT_DIR ) )
    for d in ["renpy", "renpy/game", "renpy/images/Slides", "renpy/assets/images/slides", "renpy/assets/sounds", "renpy/assets/videos", "renpy/gui", "renpy/tl" ]:
        pathlib.Path(d).mkdir( parents = True, exist_ok = True )

ntnuRevealTheme="""
/**
 * NTNU ERC theme for reveal.js
 * Author: jacky.baltes <jacky.baltes@gmail.com>
 *
 * Designed to be used with highlight.js theme
 * "monokai_sublime.css" available from
 * https://github.com/isagalaev/highlight.js/
 *
 * For other themes, change $codeBackground accordingly.
 *
 */
 
@import url(https://fonts.googleapis.com/css?family=Ubuntu:300,700,300italic,700italic);
/*********************************************
 * GLOBAL STYLES
 *********************************************/
body {
  background: #522;
  background-color: #522; }

.reveal {
  font-family: Ubuntu, "sans-serif";
  font-size: 40px;
  font-weight: normal;
  color: #eee; }

::selection {
  color: #fff;
  background: #a23;
  text-shadow: none; }

::-moz-selection {
  color: #fff;
  background: #a23;
  text-shadow: none; }

.reveal .slides section,
.reveal .slides section > section {
  line-height: 1.3;
  font-weight: inherit; }

/*********************************************
 * HEADERS
 *********************************************/
.reveal h1,
.reveal h2,
.reveal h3,
.reveal h4,
.reveal h5,
.reveal h6 {
  margin: 0 0 20px 0;
  color: #eee;
  font-family: Ubuntu, "sans-serif";
  font-weight: normal;
  line-height: 1.0;
  letter-spacing: normal;
  text-transform: uppercase;
  text-shadow: 2px 2px 2px #222;
  word-wrap: break-word;
  text-align: center; }

.reveal h1 {
  font-size: 1.80em; }

.reveal h2 {
  font-size: 1.50em; }

.reveal h3 {
  font-size: 1.25em; }

.reveal h4 {
  font-size: 1em; }

.reveal h1 {
  text-shadow: 0 1px 0 #ccc, 0 2px 0 #c9c9c9, 0 3px 0 #bbb, 0 4px 0 #b9b9b9, 0 5px 0 #aaa, 0 6px 1px rgba(0, 0, 0, 0.1), 0 0 5px rgba(0, 0, 0, 0.1), 0 1px 3px rgba(0, 0, 0, 0.3), 0 3px 5px rgba(0, 0, 0, 0.2), 0 5px 10px rgba(0, 0, 0, 0.25), 0 20px 20px rgba(0, 0, 0, 0.15); }

/*********************************************
 * OTHER
 *********************************************/
.reveal p {
  margin: 20px 0;
  line-height: 1.3; }

/* Ensure certain elements are never larger than the slide itself */
.reveal img,
.reveal video,
.reveal iframe {
  max-width: 95%;
  max-height: 95%; }

.reveal strong,
.reveal b {
  font-weight: bold; }

.reveal em {
  font-style: italic; }

.reveal ol,
.reveal dl,
.reveal ul {
  display: inline-block;
  text-align: left;
  margin: 0 0 0 1em; }

.reveal ol {
  list-style-type: decimal; }

.reveal ul {
  list-style-type: disc; }

.reveal ul ul {
  list-style-type: square; }

.reveal ul ul ul {
  list-style-type: circle; }

.reveal ul ul,
.reveal ul ol,
.reveal ol ol,
.reveal ol ul {
  display: block;
  margin-left: 40px; }

.reveal dt {
  font-weight: bold; }

.reveal dd {
  margin-left: 40px; }

.reveal blockquote {
  display: block;
  position: relative;
  width: 70%;
  margin: 20px auto;
  padding: 5px;
  font-style: italic;
  background: rgba(255, 255, 255, 0.05);
  box-shadow: 0px 0px 2px rgba(0, 0, 0, 0.2); }

.reveal blockquote p:first-child,
.reveal blockquote p:last-child {
  display: inline-block; }

.reveal q {
  font-style: italic; }

.reveal pre {
  display: block;
  position: relative;
  width: 90%;
  margin: 20px auto;
  text-align: left;
  font-size: 0.55em;
  font-family: monospace;
  line-height: 1.2em;
  word-wrap: break-word;
  box-shadow: 0px 0px 6px rgba(0, 0, 0, 0.3); }

.reveal code {
  font-family: monospace;
  text-transform: none; }

.reveal pre code {
  display: block;
  padding: 5px;
  overflow: auto;
  max-height: 400px;
  word-wrap: normal; }

.reveal table {
  margin: auto;
  border-collapse: collapse;
  border-spacing: 0; }

.reveal table th {
  font-weight: bold; }

.reveal table th,
.reveal table td {
  text-align: left;
  padding: 0.2em 0.5em 0.2em 0.5em;
  border-bottom: 1px solid; }

.reveal table th[align="center"],
.reveal table td[align="center"] {
  text-align: center; }

.reveal table th[align="right"],
.reveal table td[align="right"] {
  text-align: right; }

.reveal table tbody tr:last-child th,
.reveal table tbody tr:last-child td {
  border-bottom: none; }

.reveal sup {
  vertical-align: super;
  font-size: smaller; }

.reveal sub {
  vertical-align: sub;
  font-size: smaller; }

.reveal small {
  display: inline-block;
  font-size: 0.6em;
  line-height: 1.2em;
  vertical-align: top; }

.reveal small * {
  vertical-align: top; }

/*********************************************
 * LINKS
 *********************************************/
.reveal a {
  color: #a66;
  text-decoration: none;
  -webkit-transition: color .15s ease;
  -moz-transition: color .15s ease;
  transition: color .15s ease; }

.reveal a:hover {
  color: #dd5566;
  text-shadow: none;
  border: none; }

.reveal .roll span:after {
  color: #fff;
  background: #6a1520; }

/*********************************************
 * IMAGES
 *********************************************/
.reveal section img {
  margin: 15px 0px;
  background: rgba(255, 255, 255, 0.12);
  border: 4px solid #eee;
  box-shadow: 0 0 10px rgba(0, 0, 0, 0.15); }

.reveal section img.plain {
  border: 0;
  background: none;
  box-shadow: none; }

.reveal a img {
  -webkit-transition: all .15s linear;
  -moz-transition: all .15s linear;
  transition: all .15s linear; }

.reveal a:hover img {
  background: rgba(255, 255, 255, 0.2);
  border-color: #a23;
  box-shadow: 0 0 20px rgba(0, 0, 0, 0.55); }

/*********************************************
 * NAVIGATION CONTROLS
 *********************************************/
.reveal .controls {
  color: #a23; }

/*********************************************
 * PROGRESS BAR
 *********************************************/
.reveal .progress {
  background: rgba(0, 0, 0, 0.2);
  color: #a23; }

.reveal .progress span {
  -webkit-transition: width 800ms cubic-bezier(0.26, 0.86, 0.44, 0.985);
  -moz-transition: width 800ms cubic-bezier(0.26, 0.86, 0.44, 0.985);
  transition: width 800ms cubic-bezier(0.26, 0.86, 0.44, 0.985); }

/*********************************************
 * PRINT BACKGROUND
 *********************************************/
@media print {
  .backgrounds {
    background-color: #222; } }

.reveal p {
  font-weight: 300;
  text-shadow: 1px 1px #222; }

.reveal h1,
.reveal h2,
.reveal h3,
.reveal h4,
.reveal h5,
.reveal h6 {
  font-weight: 700; }

.reveal p code {
  background-color: #23241f;
  display: inline-block;
  border-radius: 7px; }

.reveal small code {
  vertical-align: baseline; }
  
/************************************************
 Added by Jacky Baltes
 ************************************************/
.jb-slide {
  text-align: center;
}

.jb-center {
  text-align:center;
}

.jb-very-small {
  display: inline-block;
  font-size: 0.5em;
  line-height: 1.0em;
  vertical-align: top; }
  
.jb-footer-right {
  position: absolute;
  bottom: 0px;
  right: 0px;
  width: auto;
  height: 1cm;
  max-height: 1cm;
}

.jb-footer-right-img {
  border: none;
  background: none;
  box-shadow: none;
  width: auto;
  height: 1.25cm;
}

.jb-footer-left {
  position: absolute;
  bottom: 0px;
  left: 0px;
  width: auto;
  height: 1cm;
  max-height: 1cm;
}

.jb-footer-left-img {
  border: none;
  background: none;
  box-shadow: none;
  width: auto;
  height: 1.25cm;
}

.jb-input-code {
    color: #101010;
    width: 90%;
    display: inline-block;
}

.jb-stdout {
    color: #101010;
    background: #e0e0e0;
    width: 90%;
    display: inline-block;
}
"""

with cd(ROOT_DIR):
    with open("reveal.js/css/theme/ntnuerc.css","w") as f:
        f.write(ntnuRevealTheme)

from IPython.core import magic_arguments
from IPython.core.magic import line_magic, cell_magic, line_cell_magic, Magics, magics_class
from IPython.core.display import HTML, Image, Pretty, Javascript, display
from IPython.utils.capture import capture_output

from pygments import highlight
from pygments.lexers import PythonLexer
from pygments.formatters import HtmlFormatter

#import weasyprint as wp
import io
import base64

from docutils import core, io

import zipfile
import os

# Based on reveal.js 3.7.0
REVEAL_PRESENTATION_TEMPLATE = """
<!doctype html>
<html>
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">

		<title>{{title}}</title>

		<link rel="stylesheet" href="css/reveal.css">
		<link rel="stylesheet" href="css/theme/{{THEME}}.css">

		<!-- Theme used for syntax highlighting of code -->
		<link rel="stylesheet" href="lib/css/zenburn.css">

		<!-- Printing and PDF exports -->
		<script>
			var link = document.createElement( 'link' );
			link.rel = 'stylesheet';
			link.type = 'text/css';
			link.href = window.location.search.match( /print-pdf/gi ) ? 'css/print/pdf.css' : 'css/print/paper.css';
			document.getElementsByTagName( 'head' )[0].appendChild( link );
		</script>
	</head>
	<body>
		<div class="reveal">
        <div class="slides">
            {{slides}}
        </div>
		</div>

		<script src="lib/js/head.min.js"></script>
		<script src="js/reveal.js"></script>

		<script>
			// More info about config & dependencies:
			// - https://github.com/hakimel/reveal.js#configuration
			// - https://github.com/hakimel/reveal.js#dependencies
			Reveal.initialize({
				dependencies: [
					{ src: 'plugin/markdown/marked.js' },
					{ src: 'plugin/markdown/markdown.js' },
					{ src: 'plugin/notes/notes.js', async: true },
					{ src: 'plugin/highlight/highlight.js', async: true, callback: function() { hljs.initHighlightingOnLoad(); } }
				]
			});
		</script>
	</body>
</html>
"""

REVEAL_SLIDE_TEMPLATE = """
<section id="{{id}}">

{{slideHTML}}

<aside class="notes">
{{slideNote}}
</aside>

{{slideChildren}}

</section>
"""

from urllib import request
#from google.colab import files
import pathlib
import youtube_dl

from .jbdata import JBImage, JBVideo

robbi = JBImage( name='robbi', width=162, height=138, url="https://i.postimg.cc/K81kVbvQ/ntnuerc-logo-1.png", localFile= ROOT_DIR / "reveal.js" / "assets" / "images" / "robbi.png" )
logo = JBImage( name = 'logo', width=0, height=0, url='https://i.postimg.cc/4xvjvdmq/ntnu-ee-logo.png', localFile=ROOT_DIR / "reveal.js" / "assets" / "images" / "logo.png" )

RenpyInitTemplate = """
define jb = Character("Prof. Jacky Baltes", color="#06799f", callback=speaker("jb"))
define gc = Character("Student G.C.", color="#069f67", callback=speaker("gc"))
define msG = Character("Student G.", color="#069f67", callback=speaker("msG"))

label start:
    show jb neutral at center with dissolve
    
    # Prof. Jacky's Introduction
    jb "Hello! I am Prof. Jacky Baltes."
    
    show jb neutral at center:
        linear 2.0 left
        
    jb "This project describes {{title}}."

    
    jump {{startId}}
"""

RenpyScriptTemplate = """
# Slide {{id}}
label {{label}}:
    scene bg {{id}} with {{transition}}
{{renpy}}
    jump {{right}}
"""

RenpyTransition = "fade"
RenpyInitLabel = ".init"

from .jbslide import JBSlide

import pathlib

THEME="ntnuerc"

revealSlideFooter = """
<footer>
<div class="jb-footer-left">
    <img class="jb-footer-left-img plain" src="{{ logo.url }}" alt="{{logo.name}}" />
</div>
<div class="jb-footer-right">
    <img class="jb-footer-right-img plain" src="{{ robbi.url }}" alt="{{robbi.name}}" />
</div>
</footer>
"""

#print("local css", localTheme)


email="jacky.baltes@ntnu.edu.tw"
author = """
<p>
      Jacky Baltes<br>
      National Taiwan Normal University<br>
      Taipei, Taiwan<br>
      <a href="mailto:{{email}}">{{email}}</a><br>
      {{today}}
</p>
"""

from . jbmagics import load_ipython_extension

doc = load_ipython_extension( get_ipython() )

doc.setTitle( title )
doc.setTheme('ntnuerc')
doc.setFooter( revealSlideFooter )
doc.setHeader("")

__main__.doc = doc
